### ISSUE TITLE
Optimize `comments` store

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#69]
### Phase 1: alleviate impact of multiple loops
- [ ] Remove id-to-comment mapping
    - The selectors are reconstructing array of `Comments` on each call.  It is hard to memoize given that the dependencies are often invalidated with new data.  This should be unnecessary -- reviewing with Jessop on a potential workaround.
- [ ] Move `filterComments` from selectors to views.
    - The initial assumption was that it is more efficient to filter things in one shot, rather than individually by each comment view. 
    - In hindsight, we ended filtering repeatedly because it is hard to memoize when depending on raw arrays.
    - It's easier to memo at the views since they can depend on specific values rather than the array.  Claim views are done that way too.
- [ ] Move reaction-fetch from views to actions (tag along `comment.List`)
    - A similar thing faced by `resolved` + `membership` fetches.  It's better to fetch together since we know the IDs already, instead of having to loop again to find unfetched ids.

### Phase 2: store-size reduction
- [ ] Friendlier blocklist thread 
    - Currently using the `yieldThread` method -- find better one?
- [ ] Perhaps move blocklists into a different slice?  
    - Seems unrelated to comments. It is placed here just because the calls are from Commentron.
- [ ] Use `Immer` to not invalidate the store when there is no actual change.

**Comment by infinite-persistence** [comment]
- Loops of inefficient loops (my bad)

**Comment by infinite-persistence** [comment]
These are deeply rooted, so it's a high-risk change.  Might have to wait for something big to test together,
- [ ] Remove id-to-comment mapping
    - The original implementation is similar to how we store claims -- a giant map for everything + a lighter ID-only array.  When the UI requests for comments for a claim, the comments array is reconstructed.  So 3x looping for nothing here.
        - The re-construction is happening over every page request since the store is invalidated.
    - In hindsight, there is no need for such a map because we won't be requesting comments from another claim -- it will always be per File Page.  Whatever `comment.List` gave up is already in the right sorted order.

**Comment by infinite-persistence** [comment]
- [ ] Move `filterComments` from selectors to views.
    - The initial assumption was that it is more efficient to filter things in one shot, rather than individually by each comment view. 
    - In hindsight, we ended filtering repeatedly because it is hard to memoize when depending on raw arrays.
    - It's easier to memo at the views since they can depend on specific values rather than the array.  Claim views are done that way too.
- [ ] Move reaction-fetch from views to actions (tag along `comment.List`)
    - A similar thing faced by `resolved` + `membership` fetches.  It's better to fetch together since we know the IDs already, instead of having to loop again to find unfetched ids.
